// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vemwfwzkzlunjiwsqyfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlbXdmd3premx1bmppd3NxeWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzA0MTUsImV4cCI6MjA3Mjc0NjQxNX0.09K1nDz5pMWtwaP51-YgpNWrskC1qd9S_BBozZv9fxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});